### PR TITLE
SSL stratum support

### PR DESCRIPTION
**Pull request by rplant8**
Add support for stratum+tcps
Tested on pool.rplant.xyz

### CODE REVIEW

**Comment by JayDDee** [comment]
Nice looking pool you have there, I'll have to give it a try.

I'm pretty busy right now but the change is pretty simple so I should be able to  fairly quickly.

**Comment by JayDDee** [comment]
I have a question.

I have seen different stratum notations for secure connections used. You use "stratum+tcps".
Are they all the same protocol or do the different notations represent different protocols?

**Comment by rplant8** [comment]
the pool accepts any wallets. wrong mine under the name donate.
I did on the motives of the pooler cpuminer, there's stratum+tcps.
somewhere saw still stratum+ssl, but in living nature not met

**Comment by JayDDee** [comment]
It works. It will be in the next release.

**Comment by JayDDee** [comment]
cpuminer-opt-3.10.6 is released with tcps support. Please report if there are problems.

**Comment by JayDDee** [comment]
Assume ok, no problems reported.

**Pull request closed without merging**
