### PR TITLE
Add sha256q algo

### PR DESCRIPTION
**Pull request by pyritepirate**

### CODE REVIEW

**Comment by JayDDee** [comment]
I don't need to, the existing miner is as fast as it gets.

**Comment by pyritepirate** [comment]
It's different than sha256d and sha256t, but okay I'll close the PR.

**Comment by JayDDee** [comment]
I didn't mean I won't do it. I was  just saying you already have the optimizations, essentially the
same ones I did for sha256t, so I can't make it faster. I'll get to it eventually but I have a lot of other
things going on.

I won't accept the pull but it can be used like an issue. I'll close it after the release that includes
sha256q. I may make a couple of minor changes resulting from the work I'm currently doing.

**Comment by JayDDee** [comment]
I can add sha256q fairly quickly but I have nowhere to test, it's not on the major pools.
If you can provide a place I can test it you have the shares I mine. Or I can just submit it
untested. It's so close to sha256t it's hard to mess up. You can send the mining credentials
by email if you wish.

**Comment by pyritepirate** [comment]
ok, below are mining credentials:
-a sha256q -o stratum+tcp://us.coinminingpool.org:4800 -u PRk42ijnW5UAAAZUZyUjY4bJexX9xQ9YRM

**Comment by JayDDee** [comment]
Testing in progress, so far so good.

**Comment by JayDDee** [comment]
Forcing SHA on Ryzen even when AVX2 is available.

         **********  cpuminer-opt 3.9.2  *********** 
     A CPU miner with multi algo support and optimized for CPUs
     with AES_NI and AVX2 and SHA extensions.
     BTC donation address: 12tdvfF7KmAsihBXQXynT6E6th2c2pByTT

CPU: AMD Ryzen 7 1700 Eight-Core Processor          .
SW built on Jun  2 2019 with GCC 7.4.0.
CPU features: SSE2 AES SSE4.2 AVX AVX2 SHA.
SW features: SSE2 AES SSE4.2 AVX AVX2 SHA.
Algo features: SHA.
Start mining with SHA.

[2019-06-02 09:43:10] Starting Stratum on stratum+tcp://us.coinminingpool.org:4800
[2019-06-02 09:43:10] 16 miner threads started, using 'sha256q' algorithm.
[2019-06-02 09:43:11] Stratum difficulty set to 1
[2019-06-02 09:43:11] sha256q block 48789, network diff 1174.981
[2019-06-02 09:46:11] Share 1 submitted by thread 14.
[2019-06-02 09:46:12] Accepted 1/1 (100%), diff 2.57, 52.06 MH/s, 75C
[2019-06-02 09:46:40] sha256q block 48790, network diff 1174.981
[2019-06-02 09:47:58] Share 2 submitted by thread 14.
[2019-06-02 09:47:58] Accepted 2/2 (100%), diff 1.82, 52.21 MH/s, 75C
[2019-06-02 09:48:16] Share 3 submitted by thread 5.
[2019-06-02 09:48:16] Accepted 3/3 (100%), diff 6.87, 52.21 MH/s, 75C
[2019-06-02 09:48:48] Share 4 submitted by thread 8.
[2019-06-02 09:48:48] Accepted 4/4 (100%), diff 1.94, 52.17 MH/s, 75C
[2019-06-02 09:49:36] Share 5 submitted by thread 12.
[2019-06-02 09:49:36] Accepted 5/5 (100%), diff 2.03, 52.22 MH/s, 75C
[2019-06-02 09:51:21] Share 6 submitted by thread 5.
[2019-06-02 09:51:21] Accepted 6/6 (100%), diff 1.14, 52.25 MH/s, 75C

**Comment by JayDDee** [comment]
Everything is ok with testing. Thanks for your help. I have a few more things to do before it's
released

**Comment by JayDDee** [comment]
v3.9.2 is released.If you have a Ryzen make sure you compile properly to use its
SHA feature.

Let me know of any problems.

**Comment by pyritepirate** [comment]
Thanks for including it in the latest release.

**Pull request closed without merging**
