### PR TITLE
Fix build for old version gcc

### PR DESCRIPTION
**Pull request by tengattack**
This commit could help compilation on very old version gcc, like 4.4.7.

I hope it can help.

Thanks.

### CODE REVIEW

**Comment by JayDDee** [comment]
I have several questions.

Regarding the initial issue, would it not be simpler to move the pragmas outside the function as
suggested in the error message? Does that work?

There are several other changes that appear to be unrelated to the compile problem. In some
instances they appears to break the code. Other than the obvious, like whitespace cleanup, 
can you explain these other changes?

**Comment by tengattack** [comment]
OK, I will provide the error message.
The whitespace change i didn't realize it because i do diff ignore whitespace change.

I remove white space change to make a new pr.

Thanks

**Comment by tengattack** [comment]
congifure:
`CFLAGS="-O3 -march=native -Wall -D_REENTRANT -funroll-loops -fvariable-expansion-in-unroller -fmerge-all-constants -fbranch-target-load-optimize2 -fsched2-use-superblocks -falign-loops=16 -falign-functions=16 -falign-jumps=16 -falign-labels=16" CXXFLAGS="$CFLAGS" ./configure --with-curl`

errors:
```
In file included from algo/hmq1725.c:33:
./algo/simd/sse2/nist.h:27: error: redefinition of typedef ‘uint_32t’
./algo/groestl/aes_ni/brg_types.h:80: note: previous declaration of ‘uint_32t’ was here
In file included from algo/hmq1725.c:34:
./algo/jh/sse2/jh_sse2_opt64.h:32: error: redefinition of typedef ‘BitSequence’
./algo/sha/sha3-defs.h:5: note: previous declaration of ‘BitSequence’ was here 
./algo/jh/sse2/jh_sse2_opt64.h:33: error: redefinition of typedef ‘DataLength’
./algo/sha/sha3-defs.h:6: note: previous declaration of ‘DataLength’ was here
make[2]: *** [algo/cpuminer-hmq1725.o] Error 1
```
```
algo/hodl/sha512_avx.c: In function ‘sha512ProcessBlock’: 
algo/hodl/sha512_avx.c:204: error: can't convert between vector values of different size
algo/hodl/sha512_avx.c:206: error: can't convert between vector values of different size 
make[2]: *** [algo/hodl/cpuminer-sha512_avx.o] Error 1 
```
```
In file included from algo/lyra2/lyra2rev2.c:12:
algo/lyra2/lyra2.h:25: error: redefinition of typedef ‘byte’
./algo/sha/sha3-defs.h:21: note: previous declaration of ‘byte’ was here
make[2]: *** [algo/lyra2/cpuminer-lyra2rev2.o] Error 1
```
```
algo/scrypt.c: In function ‘register_scrypt_algo’: 
algo/scrypt.c:783: error: ‘scrypt_1024_1_1_256_24way’ undeclared (first use in this function) 
algo/scrypt.c:783: error: (Each undeclared identifier is reported only once
algo/scrypt.c:783: error: for each function it appears in.)
make[2]: *** [algo/cpuminer-scrypt.o] Error 1
```
for `algo/simd/sse2/nist.h`:
```
In file included from algo/simd/sse2/vector.c:4:
algo/simd/sse2/nist.h:27: error: redefinition of typedef ‘u32’
algo/simd/sse2/compat.h:29: note: previous declaration of ‘u32’ was here
algo/simd/sse2/nist.h:28: error: redefinition of typedef ‘fft_t’
algo/simd/sse2/compat.h:99: note: previous declaration of ‘fft_t’ was here
In file included from algo/simd/sse2/nist.c:5:
algo/simd/sse2/nist.h:27: error: redefinition of typedef ‘u32’
algo/simd/sse2/compat.h:29: note: previous declaration of ‘u32’ was here
algo/simd/sse2/nist.h:28: error: redefinition of typedef ‘fft_t’
algo/simd/sse2/compat.h:99: note: previous declaration of ‘fft_t’ was here
algo/simd/sse2/vector.c:73:1: warning: "X" redefined
algo/simd/sse2/vector.c:68:1: warning: this is the location of the previous definition
make[2]: *** [algo/simd/sse2/cpuminer-nist.o] Error 1
```
for `algo/simd/sse2/compat.h`:
```
In file included from algo/timetravel10.c:18: 
./algo/simd/sse2/nist.h:36: error: expected specifier-qualifier-list before ‘u32’ 
./algo/simd/sse2/nist.h:72: error: expected ‘)’ before ‘*’ token 
./algo/simd/sse2/nist.h:73: error: expected ‘)’ before ‘*’ token 
make[2]: *** [algo/cpuminer-timetravel10.o] Error 1
```
```
In file included from ./algo/simd/sse2/nist.h:11, 
                 from algo/x11/x11evo.c:28: 
./algo/simd/sse2/compat.h:29: error: redefinition of typedef ‘uint_32t’
./algo/groestl/aes_ni/brg_types.h:80: note: previous declaration of ‘uint_32t’ was here
./algo/simd/sse2/compat.h:34: error: conflicting types for ‘uint_64t’ 
./algo/groestl/aes_ni/brg_types.h:118: note: previous declaration of ‘uint_64t’ was here 
make[2]: *** [algo/x11/cpuminer-x11evo.o] Error 1 
make[2]: *** [algo/x11/cpuminer-x11.o] Error 1
```
for `algo-gate-api.c`:
```
algo-gate-api.c: In function ‘register_algo_gate’:
algo-gate-api.c:150: error: #pragma GCC diagnostic not allowed inside functions
algo-gate-api.c:151: error: #pragma GCC diagnostic not allowed inside functions
algo-gate-api.c:215: error: #pragma GCC diagnostic not allowed inside functions
make[2]: *** [cpuminer-algo-gate-api.o] Error 1
```
for `algo/m7m.c`:
old version gmp (<4) will failed for`mp_bitcnt_t`, `mpz_inits`, `mpz_clears` undefined.

**Comment by tengattack** [comment]
Further more, some system has smaller default stack size (CentOS 6), I don't know to check it.
So I just double it in previous commit, but the new commit I have cancelled it.

You can check here:
// cpu-miner.c.patch
```
 static int thread_create(struct thr_info *thr, void* func)
 {
        int err = 0;
+       size_t stacksize;
        pthread_attr_init(&thr->attr);
+       pthread_attr_getstacksize(&thr->attr, &stacksize);
+       stacksize = 2 * stacksize;
+       pthread_attr_setstacksize(&thr->attr, stacksize);
        err = pthread_create(&thr->pth, &thr->attr, func, thr);
        pthread_attr_destroy(&thr->attr);
        return err;
}
```

**Comment by JayDDee** [comment]
Thanks for the detail. The changes are more than I am prepared to implement to support such an
old system. I am particularly concerned some of the changes could break the build for newer
systems and would require a lot of testing, more than I am preapred to do, At this time I can only
test with gcc 4.8 so I would be unable to confirm the changes don't break gcc 5 or 6. I also don't
see that you have tested all your changes beyond compilation.

Most of the changes are related to multiple definitions. I will review these individually in more
detail and may implement them as they if there are no side effects.

No other users have complained about using the miner on older systems so the benefit is
low compared to the risk.

I won't be merging the commit so you should maintain your fork for your own use.

**Comment by tengattack** [comment]
Yep, a stable build for latest system is more important.
Some of these change is magic for the GNU version.

If you have time, can review them individually.

Thanks!

**Comment by JayDDee** [comment]
I'll make the changes, with some modifications, in lyra2, simd and jh. They actually improve
the code structure. I have no idea what the problem is with hodl, but it works so I'm not touching it.
I also won't be making any changes specifically for older gcc.

The changes will be included in v3.6.7 to be released soon.

**Pull request closed without merging**
