### PR TITLE
Add algo - yespower (cryply coin)

### PR DESCRIPTION
**Pull request by bubasik**
Add algo - yespower (cryply coin)

Tested on two pool - ok (http://cryply-pool.ml, http://cpu-pool.com)

Yespower algo - https://github.com/cryply/yespower

And compile under windows.

### CODE REVIEW

**Comment by bubasik** [comment]
I'll try to make a change. But I know very little about ++. Help me.

**Comment by bubasik** [comment]
@cryptozeny only for yespower 0.9 and cryply coin.
yespower 0.5 is faster than the yescryptr16?

**Comment by cryptozeny** [comment]
solardiz said it makes faster a few

**Comment by cryptozeny** [comment]
yescrypt 0.5 will work with yesPower 0
.5 compatibel mode he said 😅

**Comment by bubasik** [comment]
@cryptozeny 
You're right. yespower 0.5 faster than yescryptr16

my tests on pentium G3250:

YESPOWER 0.5

CPU: Intel(R) Pentium(R) CPU G3250 @ 3.20GHz.
SW built on Jul 17 2018 with GCC 5.4.0.
CPU features: SSE2 SSE4.2.
SW features: SSE2 SSE4.2.
Algo features: SSE2 SHA.
Start mining with SSE2.

```
[2018-07-17 10:08:52] Starting Stratum on stratum+tcp://cpu-pool.com:63368
[2018-07-17 10:08:52] 2 miner threads started, using 'yespower' algorithm.
[2018-07-17 10:08:52] Stratum difficulty set to 0.1
[2018-07-17 10:09:46] Share submitted.
[2018-07-17 10:09:46] CPU #0: 9217 H, 184.28 H/s
[2018-07-17 10:09:46] Accepted 1/1 (100%), diff 1.84e-06, 184.28 H/s, 0C
[2018-07-17 10:10:12] Share submitted.
[2018-07-17 10:10:12] CPU #1: 13.90 kH, 181.56 H/s
[2018-07-17 10:10:12] Accepted 2/2 (100%), diff 1.85e-06, 365.84 H/s, 0C
[2018-07-17 10:10:16] Share submitted.
[2018-07-17 10:10:16] CPU #0: 5573 H, 184.47 H/s
[2018-07-17 10:10:16] Accepted 3/3 (100%), diff 3.82e-06, 366.03 H/s, 0C
[2018-07-17 10:10:33] Share submitted.
[2018-07-17 10:10:33] CPU #0: 3129 H, 185.19 H/s
[2018-07-17 10:10:33] Accepted 4/4 (100%), diff 4.1e-05, 366.75 H/s, 0C
[2018-07-17 10:10:57] Share submitted.
[2018-07-17 10:10:57] CPU #0: 4533 H, 184.90 H/s
[2018-07-17 10:10:58] Accepted 5/5 (100%), diff 4.83e-06, 366.46 H/s, 0C
```

YESCRYPTR16

```
[2018-07-17 10:05:38] Starting Stratum on stratum+tcp://cpu-pool.com:63368
[2018-07-17 10:05:38] 2 miner threads started, using 'yescryptr16' algorithm.
[2018-07-17 10:05:38] Stratum difficulty set to 0.1
[2018-07-17 10:05:43] Share submitted.
[2018-07-17 10:05:43] CPU #0: 117 H, 158.88 H/s
[2018-07-17 10:05:43] Accepted 1/1 (100%), diff 1.78e-06, 158.88 H/s, 0C
[2018-07-17 10:05:59] Share submitted.
[2018-07-17 10:05:59] CPU #0: 2663 H, 169.25 H/s
[2018-07-17 10:05:59] Accepted 2/2 (100%), diff 2.41e-06, 169.25 H/s, 0C
[2018-07-17 10:06:06] CPU #1: 4096 H, 169.75 H/s
[2018-07-17 10:06:19] Share submitted.
[2018-07-17 10:06:19] CPU #1: 2174 H, 169.78 H/s
[2018-07-17 10:06:19] Accepted 3/3 (100%), diff 2.12e-06, 339.02 H/s, 0C
[2018-07-17 10:06:41] Share submitted.
[2018-07-17 10:06:41] CPU #0: 7266 H, 169.42 H/s
[2018-07-17 10:06:42] Accepted 4/4 (100%), diff 2.9e-06, 339.19 H/s, 0C
[2018-07-17 10:07:19] CPU #1: 10.19 kH, 169.73 H/s
[2018-07-17 10:07:19] Stratum difficulty set to 0.258621
[2018-07-17 10:07:37] Share submitted.
[2018-07-17 10:07:37] CPU #0: 9288 H, 167.59 H/s
[2018-07-17 10:07:37] Accepted 5/5 (100%), diff 5.17e-06, 337.32 H/s, 0C
[2018-07-17 10:07:41] Share submitted.
[2018-07-17 10:07:41] CPU #1: 3747 H, 168.41 H/s
[2018-07-17 10:07:41] Accepted 6/6 (100%), diff 1.6e-06, 335.99 H/s, 0C
[2018-07-17 10:08:02] Share submitted.
[2018-07-17 10:08:02] CPU #1: 3580 H, 170.12 H/s
[2018-07-17 10:08:02] Accepted 7/7 (100%), diff 7.41e-06, 337.71 H/s, 0C
[2018-07-17 10:08:37] CPU #0: 10.06 kH, 168.51 H/s
```

366 h/s VS 339 h/s = yespower 0.5 faster 7%

**Comment by bubasik** [comment]
Soon I will make edits code and support for yespower 0.5.

fast hack for support yespower 0.5:
edit file _algo/yespower/yespower.c_
replace string `yespower_tls( (yespower_binary_t*)input, len, &v2, (yespower_binary_t*)output );`
to string `yespower_tls( (yespower_binary_t*)input, len, &v1, (yespower_binary_t*)output );`

and compile code. (run ./build.sh)

**Comment by cryptozeny** [comment]
@bubasik great it works and faster `7%` !! awesome :laughing:

**Comment by bubasik** [comment]
Add algo yespowerr16 (yewspower 0.5) for yenten coin
please tests
`./cpuminer  -a yespowerr16 -o stratum+tcp://cpu-pool.ml:63368 -u YENTEN_WALLET
`

**Comment by Daniel-Medeiros** [comment]
Please add support to yespower algorithm

**Comment by JayDDee** [comment]
I'm back.

I've been looking though this and I like it. But I'm not sure I understand all the names.
Is yespowerr16 a different algo from yescryptr16 or just different code for the same algo?



It looks like theyespower code  is just a better implementation of the yescrypt code. That's
great. Are you changing the name of yesscryptR16 to yespowerR16 or changing yescryptR16
to use the yespower code?

Using the yespower code for yescryptR16 is good. Can the other legacy yescrypt algos also
be converted?

**Comment by bubasik** [comment]
@JayDDee 
Yespower 1_0 - new algo
Yespower 0_5 - compatible with yescrypt

https://github.com/bellflower2015/cpuminer-opt/blob/master/algo/yespower/yespower.c

**yespower05r16 = yescryptR16**
`bool register_yespower05r16_algo( algo_gate_t* gate )
{
    paramsType = YESPOWER_PARAMS_OLDYENTEN;
    return register_yespower_algo(gate);
}`

**yespowerr16 != yescryptR16** 
`bool register_yespowerr16_algo( algo_gate_t* gate )
{
    paramsType = YESPOWER_PARAMS_YENTEN;
    return register_yespower_algo(gate);
}`

`        case YESPOWER_PARAMS_OLDYENTEN:
            params.version = YESPOWER_0_5;
            params.N = 4096;
            params.r = 16;
            params.pers = "Client Key";
            params.perslen = 10;
            break;
        case YESPOWER_PARAMS_YENTEN:
            params.version = YESPOWER_1_0;
            params.N = 4096;
            params.r = 16;
            params.pers = NULL;
            params.perslen = 0;
            break;`

Recently, the Yenten coin has moved to a new algorithm - Yespower16

Now in the Yespower 1_0 algorithm family, there is Yespower (Cranepay (ex Cryly) Coin) and YespowerR16 (Yenten Coin)

**YespowerR16:** (Yenten)
`            params.version = YESPOWER_1_0;
            params.N = 4096;
            params.r = 16;
            params.pers = NULL;
            params.perslen = 0;`

**Yespower** (Cranepay)
`            params.version = YESPOWER_1_0;
            params.N = 2048;
            params.r = 32;
            params.pers = NULL;
            params.perslen = 0;`

**Comment by JayDDee** [comment]
Good info, thanks. So I can import the yespower code, change all the legacy yescrypt algos
to use yespower 0.5, then discard the old yescrypt code?

**Comment by bubasik** [comment]
@JayDDee 
Yes ;)

**Comment by bubasik** [comment]
Latest version Yespower - https://cvsweb.openwall.com/cgi/cvsweb.cgi/projects/yespower/
(https://www.openwall.com/yespower/yespower-1.0.0.tar.gz)

**Comment by JayDDee** [comment]
I have another little question. In yespower.c:hash_yespower there is a check timestamp check to
select the yespower version for yespowerr16. I presume it is no longer required so I removed it.
Let me know if you think this will be a problem.

I'm also changing the way the parameters are set. It's simpler and will make it easier for legacy
yescrypt.

**Comment by JayDDee** [comment]
@ bubasik

Testing is going well for yespower but I'm really confused about compatibiity with yescrypt
and what that timestamp check means.

Your timecheck applies only to yespowerr16 to increment the yespower version and remove the
client key after a specific date. The selection is automatically determined by the date with no user
control. 
It looks like you mined both yescryptr16 and yespowerr16 with same configuration, ie same date.
That shouldn't work.

I tested on zpool and all yescrypt algos produce invalid shares when using yespower 0.5, they work
fine with yescrypt code.

It doesn't make sense.

**Comment by JayDDee** [comment]
I also noticed the speed of yespowe mining yescryptr16 was lower than yescrypt mining yescryptr16.
Thi is likely because I'm using a Ryzen CPU with SHA and yescrypt uses openssl/sha while
yespower uses only a SW implementation of SHA256 at this time.
I intend to enable SHA for yespower but it won't be trivial, I'll have to rename all the SHA256 function
names because they colllide with openssl. First release won't have it. I may just rip out the SW
implementation and use openssl, with or without Ryzen/SHA.

First release likely won't have yespower for yescrypt either, if ever,  due to the issue above.

**Comment by JayDDee** [comment]
SHA testing didn't go well, it's no faster on Ryzen. The speeds were so close I suspected it
wasn't using the HW SHA feature, but a test on m7m confirmed a significant improvement.

I think that's enough playing around for now, time to wrap this up. The next release will have
yespower v1.0, as is,  supporting the yespower algos using SW sha256. Yescrypt algos will
continue to be mined with the legacy yescrypt code.

**Comment by JayDDee** [comment]
cpuminer-opt 3.9.0 is released. Please test and report any problems.

**Comment by bubasik** [comment]
> I have another little question. In yespower.c:hash_yespower there is a check timestamp check to
> select the yespower version for yespowerr16. I presume it is no longer required so I removed it.
> Let me know if you think this will be a problem.
> 
> I'm also changing the way the parameters are set. It's simpler and will make it easier for legacy
> yescrypt.

Time stamp - used for hard forks Yenten Coin.
from yescryptr16 to yespowerr16.

**Comment by bubasik** [comment]
Miner not work.
The process hangs when you run any file.

Screenshot_8

**Comment by JayDDee** [comment]
I tested both yespower and yespowerr16 on an i7-4790K running Windows 8.

From the output you posted it looks like it has nothing to do with the algo but with querying the
CPU info. It could be related to the addition of support for CPU groups in v3.9.0 or it could be
your CPU. Please test another algo with v3.8.8.1 then test the same algo with 3.9.0.

**Comment by JayDDee** [comment]
> > I have another little question. In yespower.c:hash_yespower there is a check timestamp check to
> > select the yespower version for yespowerr16. I presume it is no longer required so I removed it.
> > Let me know if you think this will be a problem.
> > I'm also changing the way the parameters are set. It's simpler and will make it easier for legacy
> > yescrypt.
> 
> Time stamp - used for hard forks Yenten Coin.
> from yescryptr16 to yespowerr16.

Did you ever try mining yenten with yespower before the fork date? It's too late for that now.
Have you tried cryply fork of cpuminer with a coin that's currently yescrypt or yescryptr16?
If it work with cryply then I've done something wrong.

**Comment by bubasik** [comment]
> > Time stamp - used for hard forks Yenten Coin.
> > from yescryptr16 to yespowerr16.
> 
> Did you ever try mining yenten with yespower before the fork date? It's too late for that now.
> Have you tried cryply fork of cpuminer with a coin that's currently yescrypt or yescryptr16?
> If it work with cryply then I've done something wrong.

All right.
@bellflower2015

**Comment by bubasik** [comment]
> I tested both yespower and yespowerr16 on an i7-4790K running Windows 8.
> 
> From the output you posted it looks like it has nothing to do with the algo but with querying the
> CPU info. It could be related to the addition of support for CPU groups in v3.9.0 or it could be
> your CPU. Please test another algo with v3.8.8.1 then test the same algo with 3.9.0.
> 
> Edit: Did you use the binaries or compile yourself from source. If you compiled try the sse2 binary.

Ran the finished binary file from release.
When you run any file, even without parameters - the process hangs.

**Comment by JayDDee** [comment]
> When you run any file, even without parameters - the process hangs.

Does v3.8.8.1 also hang on all algos?

**Comment by bubasik** [comment]
> > When you run any file, even without parameters - the process hangs.
> 
> Does v3.8.8.1 also hang on all algos?
I tried it now. v3.8.8.1 - it starts well.

i5 3337u, win 7 x64 - v3.9.0 - doesn't work either

**Comment by JayDDee** [comment]
Thanks, that confirms it was a change in v3.9.0 that was not related to any particular algo.
It appears to be related to the CPU groups code change. I have no idea why you seems to be
the only one to have this problem.

I think I know how to fix it. I'm still waiting to see if any other issues pop up before releasing a fix.
Thanks for testing.

**Comment by JayDDee** [comment]
Take a look at this:

https://bitcointalk.org/index.php?topic=1326803.msg51156696#msg51156696

Same problem but only on server 2008, works on server 2012.
It works fo rme on Win8 but not for you on Win7.

I now understand the problem and am confident my solution will work.

**Comment by JayDDee** [comment]
cpuminer-opt-3.9.0.1 is released. it should fix the hanging problem. please test and report.

**Comment by bubasik** [comment]
> cpuminer-opt-3.9.0.1 is released. it should fix the hanging problem. please test and report.

checked - works well.

**Comment by JayDDee** [comment]
Thanks for all your testing.

I will drop the yescrypt compatibility issue. My testing has failed and I have no leads to pursue.
It was of limited value as the hashrate difference was likely to be within the margin of error.

**Pull request closed without merging**
