### PR TITLE
Remove singular dependency on SSE3

### PR DESCRIPTION
**Pull request by eric-ibarra**
There is only one instruction that requires SSE3 so let's add an option to use SSE2 if SSE3 is not available

### CODE REVIEW

**Comment by JayDDee** [comment]
SSSE3 is available on Intel Core2, the lowest CPU architecture currently supported by cpuminer-opt.
I'm trying to reduce the number of architectures supported so I have no interest in adding support for
old CPUs.

**Comment by JayDDee** [comment]
I'll consider making these changes in the source code but will not build additional Windows binaries.
The SSE2 binary will continue to assume SSSE3 is also included to keep it in line with Intel Core2.

I could use some help from you in indentifying the AMD CPU architectures that will benefit. In
RELEASE_NOTES there is discussion of some the the AMD CPU families that are know to be
problematic. Can you identify those that should work with these changes? Actual test results are
even better.

**Comment by JayDDee** [comment]
cpuminer-opt-3.8.4.

**Comment by eric-ibarra** [comment]
This change was specifically built and tested on the AMD Athlon(tm) 64 X2 Dual Core Processor 5200+, however, I believe the changes should apply to all processors limited to only the SSE2 instruction set.

**Pull request closed without merging**
