### PR TITLE
Add CPUpower algorithm support

### PR DESCRIPTION
**Pull request by minkcrypto**
used by CPUchain @cpuchain https://cpuchain.org

### CODE REVIEW

**Comment by JayDDee** [comment]
I took a quick look at the changes and they are very straightforward. I'll include it in the next release.
One minor change is I prefer the algos be listed in alphabetical order.

**Comment by minkcrypto** [comment]
@JayDDee Done!

**Comment by JayDDee** [comment]
I wasn't expecting you to mod the pull, but thanks.

I was thinking a bit more about the algo name. I prefer a more technical formal name. 
Since it's based on yespower is there a name that you could suggest that includes yespower? 
Your parameters are not unique so using them in the name won't work. "yespowercpu" or
"yespower-cpu" come to mind. Any thoughts? yesppower could be abbreviated to yp to shorten 
it so something like yp32cpu might work based on the rounds and pers params.

cpupower could still be an allias and I usuially don't like to include the coin name as an algo
alias. Algos often outlive the coin they are named after.

Any thoughts?

**Comment by minkcrypto** [comment]
Thanks for your advice, since we are already using the algo name `cpupower` for our miners, I would like to suggest not changing them would avoid unnecessary confusion ( they would also avoid longer names, cpupower, is also demonstrating the yespower algorithm ).

And we are also planning to change our algo in near feature, something called cpupower-new will be the next if we use our cpupower for this algo.

**Comment by JayDDee** [comment]
This changes everything. I don't do temporary algos. I'm also uncomfortable with the branding
of a generic term like "CPU" and attatching it to the algo name. That the branding is also
included in the pers parameter makes it even more likely the algo will become obsolete.
Plans to change a coin's algo is enough to make me not want to add it, but when the existing
algo carries the coin's brand it definitely won't happen. 

If that's your plan I suggest you maintain your own fork.

**Comment by minkcrypto** [comment]
You may not understand but the main reason for us to have our own algo is to prevent 51% attack from other coin miners, to prevent them changing coins from automatic switch. We've already launched our mainnet with our `cpupower` so it is your choice to support our coin or not.

**Comment by JayDDee** [comment]
I think I understand and I'm not criticizing your plan. I just prefer cpuminer-opt to be coin agnostic.

In order to maintain the control you desire you should maintain your own fork of cpuminer. You can
time the release when the algo changes. You'll have to build your own Windows binaries but I can
help with that if you're having problems.

**Comment by minkcrypto** [comment]
About algo change we are not doing it for near future, at least until the yespower is asic resistant.

What do you want me to do then? pers. and perslen. are the fixed value so there is nothing I can do with it.

Maybe I may consider changing the algo name from cpupower to yespower-cpu but it is up to you. I've told you the minimum requirements of adapting CPUchain mainnet support and merging the pr or shipping the binary is not my job.

**Comment by JayDDee** [comment]
Your plan does not fit my philosophy for cpuminer-opt and you shouldn't chnage them for me.
It's in your interest to maintain your own fork of a miner for your coin where you can maintain
control and make changes to the algo at your leisure. Whether you want to support windows users
by providing binaries is also completely your decision (and your job, not mine).

Good luck.

**Comment by JayDDee** [comment]
As previously stated the plans for this algo and coin ar emore suitable for a private miner.

**Pull request closed without merging**
