### PR TITLE
Produce smaller Docker images

### PR DESCRIPTION
**Pull request by filoozom**
At first fixed:
```
[WARNING]: Empty continuation line found in:
    RUN BUILD_DEPS="build-essential     libssl-dev 	  libgmp-dev 	  libcurl4-openssl-dev 	  libjansson-dev 	  automake" && 	  apt-get update && 	  apt-get install -y ${BUILD_DEPS}
[WARNING]: Empty continuation lines will become errors in a future release.
```

But actually changed the ```Dockerfile``` to make use of multi-stage builds to reduce final image size.

### CODE REVIEW

**Comment by JayDDee** [comment]
As I have no experience with docker I've posted a notice on bitcointalk for
feedback.

https://bitcointalk.org/index.php?topic=1326803.msg24588026#msg24588026

**Comment by filoozom** [comment]
No problem. For anyone who'd want to try easily, here's a live version on Docker Hub: https://hub.docker.com/r/filoozom/cpuminer-opt/

**Comment by filoozom** [comment]
Hi, maybe you can help with following error I'm getting while trying to compile on alpine?
```
g++  -O3 -march=native -Wall -std=gnu++11 -Lyes/lib  -Lyes/lib  -o cpuminer cpuminer-cpu-miner.o cpuminer-util.o cpuminer-uint256.o cpuminer-api.o cpuminer-sysinfos.o cpuminer-algo-gate-api.o algo/groestl/cpuminer-sph_groestl.o algo/skein/cpuminer-sph_skein.o algo/bmw/cpuminer-sph_bmw.o algo/shavite/cpuminer-sph_shavite.o algo/shavite/cpuminer-shavite.o algo/echo/cpuminer-sph_echo.o algo/blake/cpuminer-sph_blake.o algo/blake/cpuminer-sph_blake2b.o algo/heavy/cpuminer-sph_hefty1.o algo/blake/cpuminer-mod_blakecoin.o algo/luffa/cpuminer-sph_luffa.o algo/cubehash/cpuminer-sph_cubehash.o algo/simd/cpuminer-sph_simd.o algo/hamsi/cpuminer-sph_hamsi.o algo/fugue/cpuminer-sph_fugue.o algo/gost/cpuminer-sph_gost.o algo/jh/cpuminer-sph_jh.o algo/keccak/cpuminer-sph_keccak.o algo/keccak/cpuminer-keccak.o algo/sha/cpuminer-sph_sha2.o algo/sha/cpuminer-sph_sha2big.o algo/shabal/cpuminer-sph_shabal.o algo/sm3/cpuminer-sm3.o algo/whirlpool/cpuminer-sph_whirlpool.o crypto/cpuminer-blake2s.o crypto/cpuminer-oaes_lib.o crypto/cpuminer-c_keccak.o crypto/cpuminer-c_groestl.o crypto/cpuminer-c_blake256.o crypto/cpuminer-c_jh.o crypto/cpuminer-c_skein.o crypto/cpuminer-hash.o crypto/cpuminer-aesb.o crypto/cpuminer-magimath.o algo/argon2/cpuminer-argon2a.o algo/argon2/ar2/cpuminer-argon2.o algo/argon2/ar2/cpuminer-opt.o algo/argon2/ar2/cpuminer-cores.o algo/argon2/ar2/cpuminer-ar2-scrypt-jane.o algo/argon2/ar2/cpuminer-blake2b.o algo/cpuminer-axiom.o algo/blake/cpuminer-blake.o algo/blake/cpuminer-blake2b.o algo/blake/cpuminer-blake2s.o algo/blake/cpuminer-blakecoin.o algo/blake/cpuminer-decred.o algo/blake/cpuminer-pentablake.o algo/bmw/cpuminer-bmw256.o algo/cubehash/sse2/cpuminer-cubehash_sse2.o algo/cryptonight/cpuminer-cryptolight.o algo/cryptonight/cpuminer-cryptonight-common.o algo/cryptonight/cpuminer-cryptonight-aesni.o algo/cryptonight/cpuminer-cryptonight.o algo/cpuminer-drop.o algo/echo/aes_ni/cpuminer-hash.o algo/cpuminer-fresh.o algo/groestl/cpuminer-groestl.o algo/groestl/cpuminer-myr-groestl.o algo/groestl/aes_ni/cpuminer-hash-groestl.o algo/groestl/aes_ni/cpuminer-hash-groestl256.o algo/haval/cpuminer-haval.o algo/heavy/cpuminer-heavy.o algo/heavy/cpuminer-bastion.o algo/cpuminer-hmq1725.o algo/hodl/cpuminer-aes.o algo/hodl/cpuminer-hodl-gate.o algo/hodl/cpuminer-hodl-wolf.o algo/hodl/cpuminer-sha512_avx.o algo/hodl/cpuminer-sha512_avx2.o algo/jh/cpuminer-jha.o algo/cpuminer-lbry.o algo/luffa/cpuminer-luffa.o algo/luffa/sse2/cpuminer-luffa_for_sse2.o algo/lyra2/cpuminer-lyra2.o algo/lyra2/cpuminer-sponge.o algo/lyra2/cpuminer-lyra2rev2.o algo/lyra2/cpuminer-lyra2re.o algo/lyra2/cpuminer-zcoin.o algo/lyra2/cpuminer-lyra2z330.o algo/keccak/sse2/cpuminer-keccak.o algo/cpuminer-m7m.o algo/cpuminer-neoscrypt.o algo/cpuminer-nist5.o algo/cpuminer-pluck.o algo/quark/cpuminer-quark.o algo/qubit/cpuminer-qubit.o algo/qubit/cpuminer-deep.o algo/ripemd/cpuminer-sph_ripemd.o algo/cpuminer-scrypt.o algo/scryptjane/cpuminer-scrypt-jane.o algo/sha/cpuminer-sha2.o algo/sha/cpuminer-sha256t.o algo/simd/sse2/cpuminer-nist.o algo/simd/sse2/cpuminer-vector.o algo/skein/cpuminer-skein.o algo/skein/cpuminer-skein2.o algo/cpuminer-skunk.o algo/tiger/cpuminer-sph_tiger.o algo/cpuminer-timetravel.o algo/cpuminer-timetravel10.o algo/cpuminer-tribus.o algo/cpuminer-veltor.o algo/whirlpool/cpuminer-whirlpool.o algo/whirlpool/cpuminer-whirlpoolx.o algo/x11/cpuminer-phi1612.o algo/x11/cpuminer-x11.o algo/x11/cpuminer-x11evo.o algo/x11/cpuminer-x11gost.o algo/x11/cpuminer-c11.o algo/x13/cpuminer-x13.o algo/x13/cpuminer-x13sm3.o algo/x14/cpuminer-x14.o algo/x15/cpuminer-x15.o algo/x17/cpuminer-x17.o algo/cpuminer-xevan.o algo/yescrypt/cpuminer-yescrypt.o algo/yescrypt/cpuminer-sha256_Y.o algo/yescrypt/cpuminer-yescrypt-simd.o algo/cpuminer-zr5.o asm/cpuminer-neoscrypt_asm.o  asm/cpuminer-sha2-x64.o asm/cpuminer-scrypt-x64.o asm/cpuminer-aesb-x64.o   -lcurl -lz compat/jansson/libjansson.a -lpthread  -lssl -lcrypto -lgmp 
/usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libssl.so.43, needed by /usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../lib/libcurl.so, may conflict with libssl.so.1.0.0
/usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libcrypto.so.41, needed by /usr/lib/gcc/x86_64-alpine-linux-musl/6.3.0/../../../../lib/libcurl.so, may conflict with libcrypto.so.1.0.0
algo/hodl/cpuminer-sha512_avx.o: In function `sha512Compute32b_parallel':
sha512_avx.c:(.text+0x369a): undefined reference to `htobe64'
sha512_avx.c:(.text+0x36c8): undefined reference to `htobe64'
collect2: error: ld returned 1 exit status
```

**Comment by filoozom** [comment]
So, my Alpine image (`filoozom/cpuminer-opt:alpine`) is a lot smaller, but also actually quite a bit slower.
- Alpine image size: 12991468 (6 MB compressed)
- Ubuntu image size: 140381238 (55 MB compressed)

Tested with M7M on MacBook Pro (i7-3615QM) with 4 threads:
- Alpine image: 57.11 kH/s
- Ubuntu image: 59.20 kH/s

**Comment by JayDDee** [comment]
Regarding the performance drop in m7m, did you compile differently? There is now an option to
select between openssl and SPH for sha256. The version difference between Alpine and Ubuntu
doesn't seem significant.

If that's not it  are other algos also slower. If only certain algos are affected it help identify the cause.

**Comment by filoozom** [comment]
I'll run some other benchmarks. In the meantime, do you know of a clean way to `#include <endian.h>`? I'm not really that into C and even less multi-platform C so I'm not quite sure of the condition to add. Maybe something like `#ifdef __linux__`? But that seems a little bit overkill as it does work without it for other versions of Linux.

**Comment by filoozom** [comment]
A few benchmarks (would be great to have a tool for that) on i7-7700k with `-t 2`:

|   | Alpine  | Ubuntu | Note |
| - | - | - | - |
| m7m | 57 kH/s | 60 kH/s ||
| keccak | 8500 kH/s | 8350 kH/s | (varies a lot) |
| cryptonight | 173.5 H/s | 166 H/s |
| scrypt | 28 kH/s | 28 kH/s | |
| x11 | 383 kH/s | 380 kH/s | |

Seems to be fairly similar in most cases, but can definitely see the difference in some algorithms. Should maybe test it on a dedicated machine with a more powerful CPU.

**Comment by JayDDee** [comment]
Frfom the benchmark it looks like only m7m is slower with Alpine which points to either sha256
or gmp. If you benchmark skein which includes sha256 it could help narrow the problem.
If skein is also slower blame sha256. Just to remind you there are 2 configurations for sha.
The default is to use openssl (assuming it's at least 1.0.2) but a compile option USE_SPH_SHA
will use the included SPH implementation. Make sure you're comparing the same config.

**Comment by filoozom** [comment]
Updated the table in https://github.com/JayDDee/cpuminer-opt/pull/41#issuecomment-346017309, looks like it definitively is sha256. Both are compiled the same way though (just `./build.sh`), so that shouldn't be any different, and openssl versions are both `1.0.2`. Also, SPH doesn't seem to be used in either alpine nor ubuntu. Strange. Maybe something's different between `GCC 6.3.0` and `GCC 5.4.0`, but I doubt it.

Alpine:
```
CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
CPU features: SSE2 AES AVX
SW built on Nov 21 2017 with GCC 6.3.0
SW features: SSE2 AES AVX
Algo features: SSE2 SHA
Start mining with SSE2
```

Ubuntu:
```
CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
CPU features: SSE2 AES AVX
SW built on Nov 13 2017 with GCC 5.4.0
SW features: SSE2 AES AVX
Algo features: SSE2 SHA
Start mining with SSE2
```

**Comment by JayDDee** [comment]
Keeping this open as a reminder about the endian issue with hodl. I'm very busy right now with other
things so it may take a while.

**Comment by JayDDee** [comment]
I can't find a solution to the endian issue with hodl compiling on Alpine. On my system, Ubuntu-14.04
based, sys/endian.h doesn't exist. I looked for it, not found anywhere in /usr. But it compiles with
/usr/include/endian.h. Conversely I don't know why it doesn't compile on Alpine.

This is the same issue as FreeBSD. Unfortunately there is no straghtforward way to detect the
distribution.

It seems you have a way to workaround the problem. If you can find proper solution I'm open
to suggestions.

**Comment by filoozom** [comment]
It does work with `#include <endian.h>` on both Ubuntu and Alpine, doesn't it?

**Pull request closed without merging**
