### PR TITLE
Implement GR Algo AKA 'Raptoreum'

### PR DESCRIPTION
**Pull request by benda95280**
Not perfect, maybe near ? :)

Any comments / ideas / ... are welcome, as i'm discovering the dark side.

### CODE REVIEW

**Comment by JayDDee** [comment]
I don't know what you're asking. I won't merge such a huge code change for an algo I've never heard of.

**Comment by benda95280** [comment]
It's just an implementation of a RTM coin using GR Algo
Infos : https://github.com/npq7721/cpuminer-gr

**Comment by rplant8** [comment]
the coin is normal, but the algorithm is unsuccessful and the implementation is poor. no optimizations, stupid repetition of generic code 6 times. only works with -O3 and gcc<10. the benchmark doesn't work. reminded binarium_hash_v1, which worked only with keys -msse2 -O2

**Comment by rplant8** [comment]
well, the algorithm can be called cpu only if the developers of GPU miners are lazy. well, the reluctance to clean up this garbage))

**Comment by benda95280** [comment]
@rplant8 Thanks for the comments.
Could you point me in the right direction about the repetition ?
I don't have the knowledge to resolve all trouble you've said, will try to take a look on things i'm able to understand and will see :)

**Comment by benda95280** [comment]
@JayDDee 
It's just a first try to update previous code to your lastest version. I'm not asking a merge currently. If i can have a fragment of your knowledge/help on some points, i'll be happy, else will try to work on it.

**Comment by JayDDee** [comment]
I removed all the Cryptonight code from cpuminer-opt so I won't comment on that.

Rplant8 said it well, you're using slow sph versions of hash functions when there are optimized versions available.

Code reuse is fundamental to software development to avoid duplication and bloat. It's too big of a topic to discuss
here.

**Comment by JayDDee** [comment]
I have no intention of merging this even if the issues are resolved. If someone wants to take this pull off my hands you're
welcome to it. Otherwise I'll just close it.

**Comment by benda95280** [comment]
@JayDDee Going to close it, i've got some little hint here, was hopping to have more information, going on my way.

**Pull request closed without merging**
